--vim.g.copilot_assume_mapped = true
--vim.g.copilot_no_tab_map = true
--vim.keymap.set("i", "<C-I>", 'copilot#Accept("<CR>")', { silent = true, expr = true })
--vim.api.nvim_set_keymap('i', '<C-A>', 'copilot#Accept("<CR>")', {expr=true, silent=true})
--vim.g.copilot_filetypes = {
--	["*"] = false,
--	["rust"] = true,
--	["python"] = true,
--}
